create table clients (
                         id int8 generated by default as identity,
                         first_name varchar(255) not null,
                         last_name varchar(255) not null,
                         patronymic varchar(255),
                         secret_word varchar(255) not null,
                         primary key (id)
)

END