create table accounts (
                          id int8 generated by default as identity,
                          account_number int8 not null,
                          amount float8 not null,
                          opening_date timestamp not null,
                          type varchar(255) not null,
                          validity int4 not null,
                          client_id int8 not null,
                          primary key (id)
)

END

alter table if exists accounts
    add constraint FKgymog7firrf8bnoiig61666ob
    foreign key (client_id)
    references clients

END