create table orders (
                        id int8 generated by default as identity,
                        date_of_creation timestamp not null,
                        execution_result varchar(255) not null,
                        order_amount float8 not null,
                        order_type varchar(255) not null,
                        account_id int8 not null,
                        primary key (id)
)

END

alter table if exists orders
    add constraint FKagh5svlor3slbay6tq5wqor1o
    foreign key (account_id)
    references accounts

END

