create table transactions (
                              id int8 generated by default as identity,
                              date_of_creation timestamp not null,
                              execution_result varchar(255) not null,
                              total float8 not null,
                              type varchar(255) not null,
                              order_id int8 not null,
                              receive_id int8 not null,
                              sender_id int8 not null,
                              primary key (id)
)

END

alter table if exists transactions
    add constraint FKfyxndk58yiq2vpn0yd4m09kbt
    foreign key (order_id)
    references orders

END

alter table if exists transactions
    add constraint FKk30cdr2fkh9ittu0vqebqchy5
    foreign key (receive_id)
    references accounts

END

alter table if exists transactions
    add constraint FKep3ko5p4fdvnw79p1uhw2q6nf
    foreign key (sender_id)
    references accounts

END